version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12
  config: {}

filters: &filters
  tags:
    only: /.*/

# Filter for release tags.
release_filters: &release_filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  # Create a job to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  command_test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      # Run your orb's commands to validate them.
      # - config/greet

workflows:
  deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - command_test:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          name: publish-dev
          orb_name: laboperator/config-pack
          vcs_type: << pipeline.project.type >>
          requires:
            - command_test
            - orb-tools/pack
          # Use a context to hold your publishing token.
          context: orb-publishing
          filters:
            branches:
              ignore: main
      - orb-tools/publish:
          name: publish-production
          orb_name: laboperator/config-pack
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - command_test
            - orb-tools/pack
          context: orb-publishing
          filters: *release_filters
